### ISSUE TITLE
Sinhala Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/si.reactjs.org#1]
## Maintainer List

* @pavinthan
* @Suresh13
* @jayan2019
* @KogulVimal
* @puviz
* @ratheeps 
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [ ] Home Page (@pavinthan)
* [ ] Tutorial (@jdc91)

### Basics

* [x] Hello World (@isuruAb)
* [x] Introducing JSX (@TRomesh)
* [ ] Rendering Elements (@NipuniBhagya)
* [x] Components and Props (@Menuka5)
* [ ] State and Lifecycle (@dasaCoder)
* [x] Handling Events (@rexzing)
* [ ] Conditional Rendering (@asela-wijesinghe)
* [ ] Lists and Keys (@puviz)
* [x] Forms (@chathurawewelwala)
* [ ] Lifting State Up (@pupudu)
* [x] Composition vs Inheritance (@malithmcr)
* [ ] Thinking in React (@agentmilindu)

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [x] ReactDOMServer - @RizkyRajitha
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml (@pavinthan)
* [ ] docs/nav.yml (@pavinthan)

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started - @pavinduLakshan
* [x] Add React to a Website - @pavinduLakshan
* [x] Create a New React App - @pavinduLakshan
* [x] CDN Links (@dasaCoder)

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] Introducing Hooks - @pavinduLakshan
  * [ ] Hooks at a Glance
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments - @Sachin-Liyanage
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals - @Yasas4D
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [x] Web Components (@malithmcr)

### FAQ

* [x] APIs and AJAX - (@prabath95)
* [x] Babel, JSX, and Build Steps - (@Menuka5)
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS - (@Menuka5)
* [x] File Structure - (@gdsghost)
* [ ] Versioning Policy
* [x] Virtual DOM and Internals - (@Rashmildp)

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by pavinthan** [comment]
Thanks you so much @tesseralis 🙏

**Comment by tesseralis** [comment]
@pavinthan how are things going? Have you all started working on any of the pages?

**Comment by pavinthan** [comment]
@tesseralis Yes, We are working on each pages we will update Home page soon.

**Comment by jdc91** [comment]
Hi @pavinthan @tesseralis would like to contribute. Any plan on how you are dividing up the pages?

**Comment by pavinthan** [comment]
Thank you for your interest @jdc91, 
could you please help to translate [tutorial](https://reactjs.org/tutorial/tutorial.html) page ? 
once you done tutorial page we move on to next.

**Comment by tesseralis** [comment]
@jdc91 I gave you the tutorial page for now. Please let the other maintainers know if you need any help -- it's a big one. Feel free to pick one of the other pages (like "Hello world") as well if you want something smaller.

**Comment by TRomesh** [comment]
@tesseralis  @pavinthan  Hi all i would like to contribute to this and also I would like to become a maintainer of this project too.

**Comment by pavinthan** [comment]
We have done a PR to add you as maintainer to this project, 

We are moving too slow, help us to speed up our progress and use https://react-translations.slack.com this slack workspace to keep in touch.

Thanks @TRomesh

**Comment by isuruAb** [comment]
@pavinthan  @tesseralis  Hello, I would like to translate #Basics -> Hello World page

**Comment by pavinthan** [comment]
@isuruAb - updated, Thanks for your support 🙏

**Comment by tesseralis** [comment]
@pavinthan @jdc91 @TRomesh how are your translations going?

**Comment by TRomesh** [comment]
@tesseralis @pavinthan  The translation for **Thinking in React** is almost finished by the way i cannot join the  https://react-translations.slack.com slack group you guys will need to send a request.

**Comment by tesseralis** [comment]
@tromesh here! https://rt-slack-invite.herokuapp.com

**Comment by agentmilindu** [comment]
Hi @tesseralis, I would like to help with "Introducing JSX"

**Comment by pavinthan** [comment]
thanks @agentmilindu, please go ahead with that 😃

**Comment by Menuka5** [comment]
Hi @tesseralis @pavinthan  I would like to help with "Components and Props"

**Comment by asela-wijesinghe** [comment]
Hi, @pavinthan Shall i go with "Conditional rendering"

**Comment by NipuniBhagya** [comment]
Hi @pavinthan @tesseralis I would like to help with "Rendering Elements". May I proceed?

**Comment by pavinthan** [comment]
thanks @Menuka5, @asela-wijesinghe and @NipuniBhagya, please go ahead with your selections 😄

**Comment by rexzing** [comment]
Hi @pavinthan @tesseralis  I like to translate the "Handling Events" page. Shall I start the translation?

**Comment by pavinthan** [comment]
sure, thanks @rexzing, please go ahead with your selection

**Comment by dasaCoder** [comment]
Hi, I would like to translate CDN links page. Can I continue with that?

**Comment by pavinthan** [comment]
Sure, thanks @dasaCoder

**Comment by dasaCoder** [comment]
HI, I would like to translate State and Lifecycle page. Shall I proceed with that?

**Comment by pavinthan** [comment]
@dasaCoder sure, please

**Comment by chathurawewelwala** [comment]
Hi, i would like to translate Forms if you don't mind

**Comment by pavinthan** [comment]
thanks @chathurawewelwala, please go ahead with your selection

**Comment by chathurawewelwala** [comment]
thx. i start right away

**Comment by pupudu** [comment]
I'd like to jump into "Lifting State Up". One of my favourite topics in React :D 
May I? @pavinthan

**Comment by pavinthan** [comment]
Sure, thanks @pupudu

**Comment by malithmcr** [comment]
Hey @pavinthan,
I'd like to help with translations. Can I take Composition vs Inheritance? Or could you suggest me any other page?

**Comment by pavinthan** [comment]
Hey @malithmcr thanks!, please go ahead with your selection.

**Comment by pavinthan** [comment]
Hey @AuraOfDivinity thanks for your interest, you can pick any unassigned items from the list in this issue description and start translate!

**Comment by malithmcr** [comment]
Hey @pavinthan , I could help with Web Components page.

**Comment by pavinthan** [comment]
@malithmcr sure, thanks

**Comment by rexzing** [comment]
do we translate comment in code snippets? Because I found that some translations have done that. as an example https://es.reactjs.org/docs/handling-events.html.

**Comment by rexzing** [comment]
do we need to translate "Try it on CodePen" to sinhala? If so we should have a common translation isn't it?

**Comment by rexzing** [comment]
do we need to translate "Edit this page" to sinhala? If so we should have a common translation isn't it?

**Comment by malithmcr** [comment]
Hey @rexzing  I translated it like this  CodePen මත එය උත්සාහ කරන්න

😄

**Comment by pavinthan** [comment]
@rexzing Yes, we can translate any labels, thanks

**Comment by prabath95** [comment]
@tesseralis @pavinthan I would like to translate APIs and AJAX on FAQ section.

**Comment by pavinthan** [comment]
@prabath95 thanks

**Comment by Menuka5** [comment]
> Hey @rexzing I translated it like this CodePen මත එය උත්සාහ කරන්න
> 
> 😄

I will also use this on my Translations. 😄

**Comment by Menuka5** [comment]
> Hey @rexzing I translated it like this CodePen මත එය උත්සාහ කරන්න
> 
> 😄

I can't find the `Try it on CodePen` on my page. Just `[]` How can I change that?

**Comment by pavinthan** [comment]
@Menuka5 “ Try it on CodePen” word in multiple pages 
eg: `content/docs/lists-and-keys.md`

**Comment by Menuka5** [comment]
Hi @pavinthan @tesseralis I would like to Translate FAQ -> Babel, JSX, and Build Steps Page

**Comment by pavinthan** [comment]
@Menuka5, Yes please

**Comment by Menuka5** [comment]
Hi @pavinthan @tesseralis I would like to Translate FAQ -> Styling and CSS

**Comment by pavinthan** [comment]
@Menuka5, Yes please

**Comment by gdsghost** [comment]
Hi @tesseralis @pavinthan I would like to help with translating FAQ -> File Structure

**Comment by Rashmildp** [comment]
Hi @pavinthan @tesseralis I would like to contribute in translating FAQ ->Virtual DOM and Internals

**Comment by pavinthan** [comment]
@gdsghost @Rashmildp Yes please

**Comment by pavinduLakshan** [comment]
Hi @pavinthan, I would also like to contribute to translating `Installation -> Add React to a Website`

**Comment by pavinthan** [comment]
@pavinduLakshan Yes sure and thank you for your support

**Comment by pavinduLakshan** [comment]
Hi @pavinthan I will be contributing to translating `installation -> Create a New React App`

**Comment by pavinthan** [comment]
@pavinduLakshan sure please

**Comment by pavinduLakshan** [comment]
Hi @pavinthan, next I would like to translate `Introducing Hooks`.

**Comment by RizkyRajitha** [comment]
Hi @pavinthan, I would like to translate `ReactDOMServer`

**Comment by pavinthan** [comment]
@pavinduLakshan @RizkyRajitha sure please

**Comment by Sachin-Liyanage** [comment]
Hi @pavinthan , I would like to contribute to translating Advanced Guides -> Fragments.

**Comment by Sachin-Liyanage** [comment]
@pavinthan  👆👆

**Comment by pavinthan** [comment]
@Sachin-Liyanage sure please

**Comment by Yasas4D** [comment]
Hi @pavinthan,  I would like to translate `Advanced Guides -> Portals`

**Comment by pavinthan** [comment]
@Yasas4D sure please

**Comment by ksenginew** [comment]
Please release sinhala language support as soon as possible.

Ask me for any help.

**Comment by pavinthan** [comment]
Hi @ksenginew It's already there https://si.reactjs.org/ and if you want to contribute to this project, please select a topic and start to translate

**Comment by ksenginew** [comment]
> Hi @ksenginew It's already there https://si.reactjs.org/ and if you want to contribute to this project, please select a topic and start to translate

Hi @pavinthan,

It looks like even the homepage is incomplete. Can I select the home page.

And I suggest you to translate entire site using Google translate. then edit it by hand. Nowadays Google translate works finely for most situations. But it has some errors.(Yes it says "රාජ්‍ය"-rajya to "state"). We can manually fix it.

Thanks.

**Comment by ksenginew** [comment]
- [x] @pavinthan #136

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
